// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: Tab5_Basic

#include "ui.h"

lv_obj_t *ui_Screen3 = NULL;lv_obj_t *ui_Button5 = NULL;lv_obj_t *ui_Button6 = NULL;lv_obj_t *ui_Ball = NULL;lv_obj_t *ui_Arc3 = NULL;lv_obj_t *ui_Arc3Label = NULL;lv_obj_t *ui_Panel1 = NULL;lv_obj_t *ui_Container2 = NULL;lv_obj_t *ui_Button7 = NULL;lv_obj_t *ui_Label9 = NULL;lv_obj_t *ui_Button8 = NULL;lv_obj_t *ui_Label8 = NULL;lv_obj_t *ui_Button9 = NULL;lv_obj_t *ui_Label7 = NULL;lv_obj_t *ui_Button10 = NULL;lv_obj_t *ui_Label10 = NULL;lv_obj_t *ui_Button11 = NULL;lv_obj_t *ui_Label11 = NULL;
// event funtions
void ui_event_Button5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
}
}

void ui_event_Button6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      ballBaunch_Animation(ui_Ball, 0);
}
}

void ui_event_Arc3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( ui_Arc3Label, target, "", "");
}
}

// build funtions

void ui_Screen3_screen_init(void)
{
ui_Screen3 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button5 = lv_btn_create(ui_Screen3);
lv_obj_set_width( ui_Button5, 100);
lv_obj_set_height( ui_Button5, 50);
lv_obj_set_x( ui_Button5, 543 );
lv_obj_set_y( ui_Button5, -272 );
lv_obj_set_align( ui_Button5, LV_ALIGN_CENTER );

ui_Button6 = lv_btn_create(ui_Screen3);
lv_obj_set_width( ui_Button6, 100);
lv_obj_set_height( ui_Button6, 50);
lv_obj_set_x( ui_Button6, -362 );
lv_obj_set_y( ui_Button6, 231 );
lv_obj_set_align( ui_Button6, LV_ALIGN_CENTER );

ui_Ball = lv_btn_create(ui_Screen3);
lv_obj_set_width( ui_Ball, 61);
lv_obj_set_height( ui_Ball, 50);
lv_obj_set_x( ui_Ball, -362 );
lv_obj_set_y( ui_Ball, -157 );
lv_obj_set_align( ui_Ball, LV_ALIGN_BOTTOM_MID );
lv_obj_set_style_border_color(ui_Ball, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Ball, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Ball, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Ball, lv_color_hex(0x1AFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Ball, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Ball, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Ball, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Arc3 = lv_arc_create(ui_Screen3);
lv_obj_set_width( ui_Arc3, 150);
lv_obj_set_height( ui_Arc3, 150);
lv_obj_set_x( ui_Arc3, 225 );
lv_obj_set_y( ui_Arc3, -118 );
lv_obj_set_align( ui_Arc3, LV_ALIGN_CENTER );
lv_arc_set_value(ui_Arc3, 50);

ui_Arc3Label = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_Arc3Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Arc3Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Arc3Label, 220 );
lv_obj_set_y( ui_Arc3Label, -118 );
lv_obj_set_align( ui_Arc3Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Arc3Label,"00");
lv_obj_set_style_text_font(ui_Arc3Label, &ui_font_sevenSeg, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_Panel1, 50);
lv_obj_set_height( ui_Panel1, 50);
lv_obj_set_x( ui_Panel1, -263 );
lv_obj_set_y( ui_Panel1, 174 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel1, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container2 = lv_obj_create(ui_Screen3);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_width( ui_Container2, 499);
lv_obj_set_height( ui_Container2, 293);
lv_obj_set_x( ui_Container2, -367 );
lv_obj_set_y( ui_Container2, -183 );
lv_obj_set_align( ui_Container2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container2,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_Container2, LV_OBJ_FLAG_SCROLL_WITH_ARROW );   /// Flags
lv_obj_clear_flag( ui_Container2, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_Container2, LV_SCROLLBAR_MODE_ON);
lv_obj_set_scroll_dir(ui_Container2, LV_DIR_VER);

ui_Button7 = lv_btn_create(ui_Container2);
lv_obj_set_width( ui_Button7, lv_pct(100));
lv_obj_set_height( ui_Button7, lv_pct(30));
lv_obj_set_x( ui_Button7, -148 );
lv_obj_set_y( ui_Button7, -109 );
lv_obj_set_align( ui_Button7, LV_ALIGN_CENTER );
lv_obj_set_style_border_color(ui_Button7, lv_color_hex(0x0200FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Button7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Button7, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label9 = lv_label_create(ui_Button7);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );

ui_Button8 = lv_btn_create(ui_Container2);
lv_obj_set_width( ui_Button8, lv_pct(100));
lv_obj_set_height( ui_Button8, lv_pct(30));
lv_obj_set_x( ui_Button8, -142 );
lv_obj_set_y( ui_Button8, -39 );
lv_obj_set_align( ui_Button8, LV_ALIGN_CENTER );

ui_Label8 = lv_label_create(ui_Button8);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );

ui_Button9 = lv_btn_create(ui_Container2);
lv_obj_set_width( ui_Button9, lv_pct(100));
lv_obj_set_height( ui_Button9, lv_pct(30));
lv_obj_set_x( ui_Button9, 0 );
lv_obj_set_y( ui_Button9, 30 );
lv_obj_set_align( ui_Button9, LV_ALIGN_CENTER );

ui_Label7 = lv_label_create(ui_Button9);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );

ui_Button10 = lv_btn_create(ui_Container2);
lv_obj_set_width( ui_Button10, lv_pct(100));
lv_obj_set_height( ui_Button10, lv_pct(30));
lv_obj_set_x( ui_Button10, 0 );
lv_obj_set_y( ui_Button10, 30 );
lv_obj_set_align( ui_Button10, LV_ALIGN_CENTER );

ui_Label10 = lv_label_create(ui_Button10);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );

ui_Button11 = lv_btn_create(ui_Container2);
lv_obj_set_width( ui_Button11, lv_pct(100));
lv_obj_set_height( ui_Button11, lv_pct(30));
lv_obj_set_x( ui_Button11, 0 );
lv_obj_set_y( ui_Button11, 30 );
lv_obj_set_align( ui_Button11, LV_ALIGN_CENTER );

ui_Label11 = lv_label_create(ui_Button11);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Arc3, ui_event_Arc3, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
   if (ui_Screen3) lv_obj_del(ui_Screen3);

// NULL screen variables
ui_Screen3= NULL;
ui_Button5= NULL;
ui_Button6= NULL;
ui_Ball= NULL;
ui_Arc3= NULL;
ui_Arc3Label= NULL;
ui_Panel1= NULL;
ui_Container2= NULL;
ui_Button7= NULL;
ui_Label9= NULL;
ui_Button8= NULL;
ui_Label8= NULL;
ui_Button9= NULL;
ui_Label7= NULL;
ui_Button10= NULL;
ui_Label10= NULL;
ui_Button11= NULL;
ui_Label11= NULL;

}
