// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: Tab5_Basic

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t *ui_Screen3;
extern void ui_event_Button5( lv_event_t * e);
extern lv_obj_t *ui_Button5;
extern void ui_event_Button6( lv_event_t * e);
extern lv_obj_t *ui_Button6;
extern lv_obj_t *ui_Ball;
extern void ui_event_Arc3( lv_event_t * e);
extern lv_obj_t *ui_Arc3;
extern lv_obj_t *ui_Arc3Label;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_Button7;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Button8;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Button9;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Button10;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Button11;
extern lv_obj_t *ui_Label11;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

