// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: Tab5_Basic

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Image1 = NULL;lv_obj_t *ui_Arc1 = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_Label3 = NULL;lv_obj_t *ui_Spinner2 = NULL;lv_obj_t *ui_Slider1 = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_Button1 = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_Button2 = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_Button4 = NULL;
// event funtions
void ui_event_Arc1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( ui_Label1, target, "", "");
}
}

void ui_event_Button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
}
}

void ui_event_Button4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
}
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Screen1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image1, &ui_img_tokyo2025_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image1, -68 );
lv_obj_set_y( ui_Image1, -2 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Image1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Image1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Arc1 = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_Arc1, 321);
lv_obj_set_height( ui_Arc1, 321);
lv_obj_set_x( ui_Arc1, 334 );
lv_obj_set_y( ui_Arc1, -181 );
lv_obj_set_align( ui_Arc1, LV_ALIGN_CENTER );
lv_arc_set_range(ui_Arc1, 0,1000);
lv_arc_set_value(ui_Arc1, 0);

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 328 );
lv_obj_set_y( ui_Label1, -151 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_Label1,LV_LABEL_LONG_SCROLL);
lv_label_set_text(ui_Label1,"0");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xEEFB02), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_Label1, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &ui_font_sevenSeg, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Label1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 325 );
lv_obj_set_y( ui_Label3, -228 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"nikthefix");
lv_obj_set_style_text_font(ui_Label3, &ui_font_conthrax24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Spinner2 = lv_spinner_create(ui_Screen1,1000,90);
lv_obj_set_width( ui_Spinner2, 50);
lv_obj_set_height( ui_Spinner2, 50);
lv_obj_set_x( ui_Spinner2, 587 );
lv_obj_set_y( ui_Spinner2, 295 );
lv_obj_set_align( ui_Spinner2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner2, LV_OBJ_FLAG_CLICKABLE );    /// Flags

ui_Slider1 = lv_slider_create(ui_Screen1);
lv_slider_set_range(ui_Slider1, 1,255);
lv_slider_set_value( ui_Slider1, 255, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Slider1)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Slider1, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Slider1, 11);
lv_obj_set_height( ui_Slider1, 432);
lv_obj_set_x( ui_Slider1, 589 );
lv_obj_set_y( ui_Slider1, -73 );
lv_obj_set_align( ui_Slider1, LV_ALIGN_CENTER );

ui_Label4 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, 583 );
lv_obj_set_y( ui_Label4, 166 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Brightness");
lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xDA88EA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button1 = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_Button1, 146);
lv_obj_set_height( ui_Button1, 36);
lv_obj_set_x( ui_Button1, 332 );
lv_obj_set_y( ui_Button1, -66 );
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Button1, lv_color_hex(0x919191), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Button1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Button1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Button1, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x6A3F63), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Label2 = lv_label_create(ui_Button1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Automate");

ui_Button2 = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_Button2, 157);
lv_obj_set_height( ui_Button2, 50);
lv_obj_set_x( ui_Button2, 211 );
lv_obj_set_y( ui_Button2, 259 );
lv_obj_set_align( ui_Button2, LV_ALIGN_CENTER );

ui_Label5 = lv_label_create(ui_Button2);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, -2 );
lv_obj_set_y( ui_Label5, 3 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );

ui_Button4 = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_Button4, 100);
lv_obj_set_height( ui_Button4, 50);
lv_obj_set_x( ui_Button4, 185 );
lv_obj_set_y( ui_Button4, 324 );
lv_obj_set_align( ui_Button4, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_Arc1, ui_event_Arc1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Image1= NULL;
ui_Arc1= NULL;
ui_Label1= NULL;
ui_Label3= NULL;
ui_Spinner2= NULL;
ui_Slider1= NULL;
ui_Label4= NULL;
ui_Button1= NULL;
ui_Label2= NULL;
ui_Button2= NULL;
ui_Label5= NULL;
ui_Button4= NULL;

}
