// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: Tab5_Basic

#include "ui.h"

lv_obj_t *ui_Screen2 = NULL;lv_obj_t *ui_Chart1 = NULL;lv_obj_t *ui_Bar1 = NULL;lv_obj_t *ui_Button3 = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_Arc2 = NULL;
// event funtions
void ui_event_Screen2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
}
}

void ui_event_Button3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
}
}

// build funtions

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Chart1 = lv_chart_create(ui_Screen2);
lv_obj_set_width( ui_Chart1, 364);
lv_obj_set_height( ui_Chart1, 430);
lv_obj_set_x( ui_Chart1, -430 );
lv_obj_set_y( ui_Chart1, 99 );
lv_obj_set_align( ui_Chart1, LV_ALIGN_CENTER );
lv_chart_set_type( ui_Chart1, LV_CHART_TYPE_LINE);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
lv_chart_series_t* ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x808080), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_Chart1_series_1_array[] = { 0,10,20,40,80,80,40,20,10,0 };
lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);

ui_Bar1 = lv_bar_create(ui_Screen2);
lv_bar_set_value(ui_Bar1,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Bar1, 340);
lv_obj_set_height( ui_Bar1, 49);
lv_obj_set_x( ui_Bar1, -442 );
lv_obj_set_y( ui_Bar1, -194 );
lv_obj_set_align( ui_Bar1, LV_ALIGN_CENTER );

ui_Button3 = lv_btn_create(ui_Screen2);
lv_obj_set_width( ui_Button3, 100);
lv_obj_set_height( ui_Button3, 50);
lv_obj_set_x( ui_Button3, -555 );
lv_obj_set_y( ui_Button3, -298 );
lv_obj_set_align( ui_Button3, LV_ALIGN_CENTER );

ui_Label6 = lv_label_create(ui_Button3);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, 1 );
lv_obj_set_y( ui_Label6, 0 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );

ui_Arc2 = lv_arc_create(ui_Screen2);
lv_obj_set_width( ui_Arc2, 150);
lv_obj_set_height( ui_Arc2, 150);
lv_obj_set_align( ui_Arc2, LV_ALIGN_CENTER );
lv_arc_set_value(ui_Arc2, 50);

lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
   if (ui_Screen2) lv_obj_del(ui_Screen2);

// NULL screen variables
ui_Screen2= NULL;
ui_Chart1= NULL;
ui_Bar1= NULL;
ui_Button3= NULL;
ui_Label6= NULL;
ui_Arc2= NULL;

}
